### ISSUE TITLE
Missing exposed methods

### ISSUE THREAD

**Issue by hash-bang** [CMP2804M-Group3/kodi-controller#85]
The `rewind` + `fastForward` methods are not exposed as methods on the instantiated controller:

```javascript
var KodiController = require('kodi-controller');
var kodi = new KodiController('10.0.0.1', '8080');
console.log(kodi);
```

Dumps:
```
KODI Controller {
  url: 'http://10.0.0.1:8080/jsonrpc',
  getActivePlayerID: [Function: getActivePlayerID],
  pause: [Function: pause],
  play: [Function: play],
  playPause: [Function: playPause],
  stop: [Function: stop],
  contextMenu: [Function: contextMenu],
  select: [Function: select],
  goBack: [Function: goBack],
  goHome: [Function: goHome],
  goNext: [Function: goNext],
  goPrevious: [Function: goPrevious],
  goUp: [Function: goUp],
  goDown: [Function: goDown],
  goLeft: [Function: goLeft],
  goRight: [Function: goRight],
  toggleFullscreen: [Function: toggleFullscreen],
  toggleMute: [Function: toggleMute],
  toggleShuffle: [Function: toggleShuffle]
}
```

**Comment by hash-bang** [comment]
Also `setVolume`

**Comment by Pittsy24** [comment]
That is odd, we are exporting the entire class at the bottom with module.exports = Controller;. 
Did you download the package from NPM or did you download the GitHub source @hash-bang?

**Comment by meharryp** [comment]
Seemingly unable to reproduce this myself, what node version are you using, and are you using the git version or the npm version?

**Comment by hash-bang** [comment]
I'm using the latest NPM version. Maybe the changes we're made but it hasn't been published?

**Comment by meharryp** [comment]
Gonna push the new version to npm pretty soon, but I've tested with both the npm and git versions and just can't reproduce it at all. The release build of https://github.com/CMP2804M-Group3/Kontrol uses the npm version and works completely fine on my end.

**Comment by hash-bang** [comment]
Actually, the problem may be at my end. I was remapping the callbacks into functions and the method I was using choked on a few of of those class methods for some reason.

Sorry, my bad.
